exports.dictionary = {
	"round_biggestfan":                 					{name: "Big Fans", 				type:"Race", 		season: 2, icon:"/images/roundicons/Race/UI_Medal_Icon_BigFans.webp"},
	"round_satellitehoppers_almond":    					{name: "Cosmic Highway", 		type:"Race", 		season: 8, icon:"/images/roundicons/Race/Icon_CosmicHighway.webp"},
	"round_door_dash":	                 					{name: "Door Dash", 			type:"Race", 		season: 1, icon:"/images/roundicons/Race/UI_Medal_Icon_DoorDash.webp"},
	"round_gauntlet_02":                					{name: "Dizzy Heights", 		type:"Race", 		season: 1, icon:"/images/roundicons/Race/UI_Medal_Icon_DizzyHeights.webp"},
	"round_iceclimb":                   					{name: "Freezy Peak", 			type:"Race", 		season: 3, icon:"/images/roundicons/Race/UI_Medal_Icon_FreezyPeak.webp"},
	"round_dodge_fall":                 					{name: "Fruit Chute", 			type:"Race", 		season: 1, icon:"/images/roundicons/Race/UI_Medal_Icon_FruitChute.webp"},
	"round_see_saw_360":                					{name: "Full Tilt", 			type:"Race", 		season: 6, icon:"/images/roundicons/Race/Icon_Full_Tilt.webp"},
	"round_chompchomp":                 					{name: "Gate Crash", 			type:"Race", 		season: 1, icon:"/images/roundicons/Race/UI_Medal_Icon_GateCrash.webp"},
	"round_gauntlet_01":                					{name: "Hit Parade", 			type:"Race", 		season: 1, icon:"/images/roundicons/Race/UI_Medal_Icon_HitParade.webp"},
	"round_gauntlet_04":                					{name: "Knight Fever", 			type:"Race", 		season: 2, icon:"/images/roundicons/Race/UI_Medal_Icon_KnightFever.webp"},
	"round_drumtop":                    					{name: "Lily Leapers", 			type:"Race", 		season: 5, icon:"/images/roundicons/Race/UI_Medal_Icon_LilyLeapers.webp"},
	"round_gauntlet_08":                					{name: "Party Promenade", 		type:"Race", 		season: 6, icon:"/images/roundicons/Race/Icon_Party_Promenade.webp"},
	"round_pipedup_s6_launch":          					{name: "Pipe Dream", 			type:"Race", 		season: 6, icon:"/images/roundicons/Race/Icon_Pipe_Dream.webp"},
	"round_pixelperfect_almond":        					{name: "Pixel Painters", 		type:"Race", 		season: 8, icon:"/images/roundicons/Race/Icon_Pixel_Painters.webp"},
	"round_follow_the_line":            					{name: "Puzzle Path", 			type:"Race", 		season: 9, icon:"/images/roundicons/Race/Icon_Puzzle_Path.webp"},
	"round_tunnel_race":                					{name: "Roll On", 				type:"Race", 		season: 4, icon:"/images/roundicons/Race/UI_Medal_Icon_RollOn.webp"},
	"round_see_saw":                    					{name: "See Saw", 				type:"Race", 		season: 1, icon:"/images/roundicons/Race/UI_Medal_Icon_SeeSaw.webp"},
	"round_shortcircuit":               					{name: "Short Circuit", 		type:"Race", 		season: 4, icon:"/images/roundicons/Race/UI_Medal_Icon_ShortCircuit.webp"},
	"round_gauntlet_06":                					{name: "Skyline Stumble", 		type:"Race", 		season: 4, icon:"/images/roundicons/Race/UI_Medal_Icon_SkylineStumble.webp"},
	"round_lava":                       					{name: "Slime Climb", 			type:"Race", 		season: 1, icon:"/images/roundicons/Race/UI_Medal_Icon_SlimeClimb.webp"},
	"round_slimeclimb_2":               					{name: "The Slimescraper", 		type:"Race", 		season: 4, icon:"/images/roundicons/Race/UI_Medal_Icon_TheSlimescraper.webp"},
	"round_gauntlet_10_almond":         					{name: "Space Race", 			type:"Race", 		season: 8, icon:"/images/roundicons/Race/Icon_SpaceRace.webp"},
	"round_slide_chute":                					{name: "Speed Slider", 			type:"Race", 		season: 9, icon:"/images/roundicons/Race/Icon_Speed_Slider.webp"},
	"round_short_circuit_2_symphony_launch_show": 			{name: "Speed Circuit", 		type:"Race", 		season: 7, icon:"/images/roundicons/Race/Icon_Speed_Circuit.webp"},
	"round_starlink_almond":            					{name: "Starchart", 			type:"Race", 		season: 8, icon:"/images/roundicons/Race/Icon_Starchart.webp"},
	"round_tip_toe":                    					{name: "Tip Toe", 				type:"Race", 		season: 1, icon:"/images/roundicons/Race/UI_Medal_Icon_TipToe.webp"},
	"round_gauntlet_09_symphony_launch_show": 				{name: "Track Attack", 			type:"Race", 		season: 7, icon:"/images/roundicons/Race/Icon_Track_Attack.webp"},
	"round_gauntlet_07":                					{name: "Treetop Tumble", 		type:"Race", 		season: 5, icon:"/images/roundicons/Race/UI_Medal_Icon_TreetopTumble.webp"},
	"round_gauntlet_05":                					{name: "Tundra Run", 			type:"Race", 		season: 3, icon:"/images/roundicons/Race/UI_Medal_Icon_TundraRun.webp"},
	"round_gauntlet_03":                					{name: "Whirlygig", 			type:"Race", 		season: 1, icon:"/images/roundicons/Race/UI_Medal_Icon_TheWhirlygig.webp"},
	"round_wall_guys":                  					{name: "Wall Guys", 			type:"Race", 		season: 2, icon:"/images/roundicons/Race/UI_Medal_Icon_WallGuys.webp"},
	"round_airtime":                    					{name: "Airtime", 				type:"Hunt", 		season: 6, icon:"/images/roundicons/Hunt/Icon_Airtime.webp"},
	"round_bluejay":                    					{name: "Bean Hill Zone", 		type:"Hunt", 		season: 7, icon:"/images/roundicons/Hunt/Icon_Bean_Hill_Zone.webp"},
	"round_hoops_revenge_symphony_launch_show": 			{name: "Bounce Party", 			type:"Hunt", 		season: 7, icon:"/images/roundicons/Hunt/Icon_Bounce_Party.webp"},
	"round_king_of_the_hill":           					{name: "Bubble Trouble", 		type:"Hunt", 		season: 5, icon:"/images/roundicons/Hunt/UI_Medal_Icon_BubbleTrouble.webp"},
	"round_1v1_button_basher":          					{name: "Button Bashers", 		type:"Hunt", 		season: 4, icon:"/images/roundicons/Hunt/UI_Medal_Icon_ButtonBashers.webp"},
	"round_ffa_button_bashers_squads_almond": 				{name: "Frantic Factory", 		type:"Hunt", 		season: 8, icon:"/images/roundicons/Hunt/Icon_Frantic_Factory.webp"},
	"round_slippy_slide":               					{name: "Hoop Chute", 			type:"Hunt", 		season: 9, icon:"/images/roundicons/Hunt/Icon_Hoop_Chute.webp"},
	"round_hoops_blockade_solo":        					{name: "Hoopsie Legends", 		type:"Hunt", 		season: 2, icon:"/images/roundicons/Hunt/UI_Medal_Icon_HoopsieLegends.webp"},
	"round_follow-the-leader_s6_launch":					{name: "Leading Light", 		type:"Hunt", 		season: 6, icon:"/images/roundicons/Hunt/Icon_Leading_Light.webp"},
	"round_penguin_solos":              					{name: "Pegwin Pool Party", 	type:"Hunt", 		season: 5, icon:"/images/roundicons/Hunt/UI_Medal_Icon_PegwinPoolParty.webp"},
	"round_skeefall":                   					{name: "Ski Fall", 				type:"Hunt", 		season: 3, icon:"/images/roundicons/Hunt/UI_Medal_Icon_SkiFall.webp"},
	"round_fruitpunch_s4_show":         					{name: "Big Shots", 			type:"Survival", 	season: 4, icon:"/images/roundicons/Survival/UI_Medal_Icon_BigShots.webp"},
	"round_blastballruins":             					{name: "Blastlantis", 			type:"Survival", 	season: 9, icon:"/images/roundicons/Survival/Icon_Blastlantis.webp"},
	"round_block_party":                					{name: "Block Party", 			type:"Survival", 	season: 1, icon:"/images/roundicons/Survival/UI_Medal_Icon_BlockParty.webp"},
	"round_hoverboardsurvival_s4_show": 					{name: "Hoverboard Heroes", 	type:"Survival", 	season: 4, icon:"/images/roundicons/Survival/UI_Medal_Icon_HoverboardHeroes.webp"},
	"round_hoverboardsurvival2_almond": 					{name: "Hyperdrive Heroes", 	type:"Survival", 	season: 8, icon:"/images/roundicons/Survival/Icon_Hyperdrive_Heroes.webp"},
	"round_jump_club":                  					{name: "Jump Club",				type:"Survival", 	season: 1, icon:"/images/roundicons/Survival/UI_Medal_Icon_JumpClub.webp"},
	"round_tunnel":                     					{name: "Roll Out", 				type:"Survival", 	season: 1, icon:"/images/roundicons/Survival/UI_Medal_Icon_RollOut.webp"},
	"round_snowballsurvival":           					{name: "Snowball Survival", 	type:"Survival", 	season: 3, icon:"/images/roundicons/Survival/UI_Medal_Icon_SnowballSurvival.webp"},
	"round_robotrampage_arena_2":       					{name: "Stompin' Ground", 		type:"Survival", 	season: 5, icon:"/images/roundicons/Survival/UI_Medal_Icon_StompinGround.webp"},
	"round_tail_tag":                   					{name: "Tail Tag", 				type:"Hunt", 		season: 1, icon:"/images/roundicons/Hunt/UI_Medal_Icon_TailTag.webp"},
	"round_spin_ring_symphony_launch_show": 				{name: "The Swiveller", 		type:"Survival", 	season: 7, icon:"/images/roundicons/Survival/Icon_The_Swiveller.webp"},
	"round_1v1_volleyfall_symphony_launch_show": 			{name: "Volleyfall", 			type:"Hunt", 		season: 7, icon:"/images/roundicons/Hunt/Icon_Volleyfall.webp"},
	"round_match_fall":                 					{name: "Perfect Match", 		type:"Logic", 		season: 1, icon:"/images/roundicons/Logic/UI_Medal_Icon_PerfectMatch.webp"},
	"round_fruit_bowl":                 					{name: "Sum Fruit", 			type:"Logic", 		season: 5, icon:"/images/roundicons/Logic/UI_Medal_Icon_SumFruit.webp"},
	"round_basketfall_s4_show":         					{name: "Basketfall", 			type:"Team", 		season: 4, icon:"/images/roundicons/Team/UI_Medal_Icon_Basketfall.webp"},
	"round_egg_grab":                   					{name: "Egg Scramble", 			type:"Team", 		season: 1, icon:"/images/roundicons/Team/UI_Medal_Icon_EggScramble.webp"},
	"round_egg_grab_02":                					{name: "Egg Siege", 			type:"Team", 		season: 2, icon:"/images/roundicons/Team/UI_Medal_Icon_EggSiege.webp"},
	"round_fall_ball_60_players":       					{name: "Fall Ball", 			type:"Team", 		season: 1, icon:"/images/roundicons/Team/UI_Medal_Icon_FallBall.webp"},
	"round_ballhogs":                   					{name: "Hoarders", 				type:"Team", 		season: 1, icon:"/images/roundicons/Team/UI_Medal_Icon_Hoarders.webp"},
	"round_hoops":                      					{name: "Hoopsie Daisy", 		type:"Team", 		season: 1, icon:"/images/roundicons/Team/UI_Medal_Icon_HoopsieDaisy.webp"},
	"round_jinxed":                     					{name: "Jinxed", 				type:"Team", 		season: 1, icon:"/images/roundicons/Team/UI_Medal_Icon_Jinxed.webp"},
	"round_chicken_chase":              					{name: "Pegwin Pursuit", 		type:"Team", 		season: 3, icon:"/images/roundicons/Team/UI_Medal_Icon_PegwinPursuit.webp"},
	"round_territory_control_s4_show":  					{name: "Power Trip", 			type:"Team", 		season: 4, icon:"/images/roundicons/Team/UI_Medal_Icon_PowerTrip.webp"},
	"round_rocknroll":                  					{name: "Rock 'n' Roll", 		type:"Team", 		season: 1, icon:"/images/roundicons/Team/UI_Medal_Icon_RocknRoll.webp"},
	"round_snowy_scrap":                					{name: "Snowy Scrap", 			type:"Team", 		season: 3, icon:"/images/roundicons/Team/UI_Medal_Icon_SnowyScrap.webp"},
	"round_conveyor_arena":             					{name: "Team Tail Tag", 		type:"Team", 		season: 1, icon:"/images/roundicons/Team/UI_Medal_Icon_TeamTailTag.webp"},
	"round_invisibeans":                					{name: "Sweet Thieves", 		type:"Invisibeans", season: 6, icon:"/images/roundicons/Invisibeans/Icon_Sweet_Thieves.webp"},
	"round_pumpkin_pie":                					{name: "Treat Thieves", 		type:"Invisibeans", season: 8, icon:"/images/roundicons/Invisibeans/Icon_Treat_Thieves.webp"},
	"round_blastball_arenasurvival_symphony_launch_show": 	{name: "Blast Ball", 			type:"Final", 		season: 7, icon:"/images/roundicons/Final/Icon_Blast_Ball.webp"},
	"round_fall_mountain_hub_complete": 					{name: "Fall Mountain", 		type:"Final", 		season: 1, icon:"/images/roundicons/Final/UI_Medal_Icon_FallMountain.webp"},
	"round_floor_fall":                 					{name: "Hex-A-Gone", 			type:"Final", 		season: 1, icon:"/images/roundicons/Final/UI_Medal_Icon_HexAGone.webp"},
	"round_hexaring_symphony_launch_show": 					{name: "Hex-A-Ring", 			type:"Final", 		season: 7, icon:"/images/roundicons/Final/Icon_Hex-A-Ring.webp"},
	"round_hexsnake_almond":            					{name: "Hex-A-Terrestrial", 	type:"Final", 		season: 8, icon:"/images/roundicons/Final/Icon_Hex-A-Terrestrial.webp"},
	"round_jump_showdown":              					{name: "Jump Showdown", 		type:"Final", 		season: 1, icon:"/images/roundicons/Final/UI_Medal_Icon_JumpShowdown.webp"},
	"round_kraken_attack":              					{name: "Kraken Slam", 			type:"Final", 		season: 9, icon:"/images/roundicons/Final/Icon_Kraken_Slam.webp"},
	"round_crown_maze":                 					{name: "Lost Temple", 			type:"Final", 		season: 5, icon:"/images/roundicons/Final/UI_Medal_Icon_LostTemple.webp"},
	"round_tunnel_final":	              					{name: "Roll Off", 				type:"Final", 		season: 3, icon:"/images/roundicons/Final/UI_Medal_Icon_RollOff.webp"},
	"round_royal_rumble":               					{name: "Royal Fumble", 			type:"Final", 		season: 1, icon:"/images/roundicons/Final/UI_Medal_Icon_RoyalFumble.webp"},
	"round_thin_ice":                   					{name: "Thin Ice", 				type:"Final", 		season: 3, icon:"/images/roundicons/Final/UI_Medal_Icon_ThinIce.webp"},
	"round_tiptoefinale_almond":        					{name: "Tip Toe Finale", 		type:"Final", 		season: 8, icon:"/images/roundicons/Final/Icon_TipToeFinale.webp"},

	"wle_s10_round_share_code":         					{name:"Creative Custom", 		type:"Creative", 	season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},     
    "wle_s10_orig_round_001":           					{name:"Beans Ahoy!", 			type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_002":           					{name:"Airborne Antics", 		type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_003":           					{name:"Scythes & Roundabouts", 	type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_004":           					{name:"Cardio Runners", 		type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_005":           					{name:"Fan Flingers", 			type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_006":           					{name:"Uphill Struggle", 		type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_007":           					{name:"Spinner Sprint", 		type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_008":           					{name:"Lane Changers", 			type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_009":           					{name:"Gentle Gauntlet", 		type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_012":           					{name:"Up & Down", 				type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_013":           					{name:"Choo Choo Challenge", 	type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_014":           					{name:"Runner Beans", 			type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_015":           					{name:"Disc Dashers", 			type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_016":           					{name:"Two Faced", 				type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_019":           					{name:"Blueberry Bombardment", 	type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_020":           					{name:"Chuting Stars", 			type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_021":           					{name:"Slimy Slopes", 			type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_022":           					{name:"Circuit Breakers", 		type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_023":           					{name:"Winding Walkways", 		type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_026":           					{name:"Hyperlink Hijinks", 		type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_027":           					{name:"Fan Frolics", 			type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_028":           					{name:"Windmill Road", 			type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_029":           					{name:"Conveyor Clash", 		type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_032":           					{name:"Fortress Frolics", 		type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_033":           					{name:"Super Door Dash", 		type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_034":           					{name:"Spiral Of Woo", 			type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_035":           					{name:"Tornado Trial", 			type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_036":           					{name:"Hopscotch Havoc", 		type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_037":           					{name:"Beat Bouncers", 			type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_038":           					{name:"Blunder Bridges", 		type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_039":           					{name:"Incline Rewind", 		type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_040":           					{name:"Prismatic Parade", 		type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_041":           					{name:"Swept Away", 			type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_042":           					{name:"Balancing Act", 			type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_043":           					{name:"Trouble Tower", 			type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_044":           					{name:"Serpent Slalom", 		type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_045":           					{name:"Floorless", 				type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_046":           					{name:"In The Cloud", 			type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_047":           					{name:"Downstream Duel", 		type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_048":           					{name:"Lost Palace", 			type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_round_001":                					{name:"Digi Trek", 				type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_round_002":                					{name:"Shortcut Links", 		type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_round_003":                					{name:"Upload Heights", 		type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_round_005":                					{name:"Data Streams", 			type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_round_006":                					{name:"Gigabyte Gauntlet", 		type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_round_007":                					{name:"Cube Corruption", 		type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_round_008":                					{name:"Wham Bam Boom", 			type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_round_010":                					{name:"Pixel Hearts", 			type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_round_011":                					{name:"Cyber Circuit", 			type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_round_012":                					{name:"Boom Blaster Trial", 	type:"Race", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_010":           					{name:"Square Up", 				type:"Final", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_011":           					{name:"Slide Showdown", 		type:"Final", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_017":           					{name:"Bellyflop Battlers", 	type:"Final", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_018":           					{name:"Apples & Oranges", 		type:"Final", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_024":           					{name:"Wooseleum", 				type:"Final", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_025":           					{name:"Mount Boom", 			type:"Final", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_030":           					{name:"Mega Monument", 			type:"Final", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_orig_round_031":           					{name:"Transfer Turnpike", 		type:"Final", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_round_004":                					{name:"Parkour Panic", 			type:"Final", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},
    "wle_s10_round_009":                					{name:"Firewall Finale", 		type:"Final", 		season:10, icon:"/images/roundicons/Creative/icon_Gauntlet.png"},

};
exports.notFound = {
	name: "Not Found",
	type: "Unknown",
	season: 0,
	icon:"/images/roundicons/default.png"
}
exports.aliases = {
	"round_thin_ice":[
		"round_thin_ice",
		"round_thin_ice_mini",
		"round_thin_ice_low_grav",
		"round_thin_ice_mini_low_grav"		
	],
	"round_thin_ice_mini":[
		"round_thin_ice",
		"round_thin_ice_mini",
		"round_thin_ice_low_grav",
		"round_thin_ice_mini_low_grav"		
	],
	"round_thin_ice_low_grav":[
		"round_thin_ice",
		"round_thin_ice_mini",
		"round_thin_ice_low_grav",
		"round_thin_ice_mini_low_grav"		
	],
	"round_thin_ice_mini_low_grav":[
		"round_thin_ice",
		"round_thin_ice_mini",
		"round_thin_ice_low_grav",
		"round_thin_ice_mini_low_grav"		
	],
	"round_floor_fall":[
		"round_floor_fall",
		"round_floor_fall_mini",
		"round_floor_fall_low_grav",
		"round_floor_fall_mini_low_grav"		
	],
	"round_floor_fall_mini":[
		"round_floor_fall",
		"round_floor_fall_mini",
		"round_floor_fall_low_grav",
		"round_floor_fall_mini_low_grav"		
	],
	"round_floor_fall_low_grav":[
		"round_floor_fall",
		"round_floor_fall_mini",
		"round_floor_fall_low_grav",
		"round_floor_fall_mini_low_grav"		
	],
	"round_floor_fall_mini_low_grav":[
		"round_floor_fall",
		"round_floor_fall_mini",
		"round_floor_fall_low_grav",
		"round_floor_fall_mini_low_grav"		
	]	
}
var illegalRounds = {
};
exports.isLegal = function (round){
	if(illegalRounds[round]){
		return false;
	}else{
		return true;
	}
};